name: Creating Node.js app. image and deploying it to Docker Hub
on:
  push:
    branches:
    - test-ci-node
    
jobs: 
  build:  
    name: Build Image
    runs-on: ubuntu-latest
   
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DANIEL_DOCKER_USERNAME }}
        password: ${{ secrets.DANIEL_DOCKER_PASSWORD }}
        
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DANIEL_GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta 
      uses: docker/metadata-action@v3
      with:
        images: |
          danielmedou/myapprestaurant
          ghcr.io/${{ github.daniel-package }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
