name: trivy-scanning

on:
  push:
    branches: [ test-ci-node" ]
  pull_request:
    branches: [ "test-ci-node" ]
#  schedule:
 #   - cron: '41 16 * * 0'

permissions: write-all

jobs:
  trivy-scanning-job:
    name: trivy-sec-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@test-ci-node
        with:
          scan-type: 'fs'
          ignore-unfixed: true 
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Build an image from Dockerfile
        #run: |
          #docker build -t docker.io/devops-counsel/py-app:${{ github.sha }} .
        run: |
          docker build -t docker.io/trivy-sacn:${{ github.sha }} .
        #uses: docker/build-push-action@v5
        #with:
          #context: .
          #file: ./Dockerfile
          #push: true
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          #image-ref: 'docker.io/devops-counsel/py-app:${{ github.sha }}'
          image-ref: 'docker.io/trivy-sacn:${{ github.sha }}'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
